### ISSUE TITLE
Flair-registry - java.lang.NullPointerException: null 

### ISSUE THREAD

**Issue by fabiofilz** [viz-centric/flair-helm-charts#9] opened 2020-04-15 13:50 UTC
Hi @admin-vizcentric,

The log of flair-registry is returning java.lang.NullPointerException: null every 5 seconds.

Could you please check the reason?

Thank you.
Fabio

`╰─➤  stern flair-registry                                                                                                                                                                     127 ↵
+ flair-registry-74fbd79fb5-z2lcc › flair-registry
flair-registry-74fbd79fb5-z2lcc flair-registry The application will start in 0s...
flair-registry-74fbd79fb5-z2lcc flair-registry WARNING: An illegal reflective access operation has occurred
flair-registry-74fbd79fb5-z2lcc flair-registry WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/app.war!/WEB-INF/lib/spring-core-5.0.10.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
flair-registry-74fbd79fb5-z2lcc flair-registry WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
flair-registry-74fbd79fb5-z2lcc flair-registry WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
flair-registry-74fbd79fb5-z2lcc flair-registry WARNING: All illegal access operations will be denied in a future release
flair-registry-74fbd79fb5-z2lcc flair-registry
flair-registry-74fbd79fb5-z2lcc flair-registry         ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
flair-registry-74fbd79fb5-z2lcc flair-registry         ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
flair-registry-74fbd79fb5-z2lcc flair-registry         ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
flair-registry-74fbd79fb5-z2lcc flair-registry   ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
flair-registry-74fbd79fb5-z2lcc flair-registry   ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
flair-registry-74fbd79fb5-z2lcc flair-registry    ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
flair-registry-74fbd79fb5-z2lcc flair-registry
flair-registry-74fbd79fb5-z2lcc flair-registry :: JHipster Registry :: Running Spring Boot 2.0.6.RELEASE ::
flair-registry-74fbd79fb5-z2lcc flair-registry :: https://www.jhipster.tech ::
flair-registry-74fbd79fb5-z2lcc flair-registry
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:36.610  INFO 7 --- [           main] i.g.j.registry.JHipsterRegistryApp       : The following profiles are active: composite,prod,private
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:43.293  WARN 7 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:46.047  INFO 7 --- [           main] i.g.j.registry.config.WebConfigurer      : Web application configuration, using profiles: composite
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:46.070  INFO 7 --- [           main] i.g.j.registry.config.WebConfigurer      : Web application fully configured
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:48.056  WARN 7 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:51.892  INFO 7 --- [           main] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:51.893  INFO 7 --- [           main] com.netflix.discovery.DiscoveryClient    : Client configured to neither register nor query for data.
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:51.904  INFO 7 --- [           main] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1586954691902 with initial instances count: 0
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:52.062  INFO 7 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:52.063  INFO 7 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:52.063  INFO 7 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:52.063  INFO 7 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:53.315  INFO 7 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:53.317  INFO 7 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:53.317  INFO 7 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:53.317  INFO 7 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:54.171  INFO 7 --- [           main] i.g.j.registry.JHipsterRegistryApp       : Started JHipsterRegistryApp in 25.167 seconds (JVM running for 26.279)
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:54.189  INFO 7 --- [           main] i.g.j.registry.JHipsterRegistryApp       :
flair-registry-74fbd79fb5-z2lcc flair-registry ----------------------------------------------------------
flair-registry-74fbd79fb5-z2lcc flair-registry 	Application 'jhipster-registry' is running! Access URLs:
flair-registry-74fbd79fb5-z2lcc flair-registry 	Local: 		http://localhost:8761
flair-registry-74fbd79fb5-z2lcc flair-registry 	External: 	http://10.77.32.36:8761
flair-registry-74fbd79fb5-z2lcc flair-registry 	Profile(s): 	[composite, prod, private]
flair-registry-74fbd79fb5-z2lcc flair-registry ----------------------------------------------------------
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:44:54.189  INFO 7 --- [           main] i.g.j.registry.JHipsterRegistryApp       :
flair-registry-74fbd79fb5-z2lcc flair-registry ----------------------------------------------------------
flair-registry-74fbd79fb5-z2lcc flair-registry 	Config Server: 	Connected to the JHipster Registry config server!
flair-registry-74fbd79fb5-z2lcc flair-registry ----------------------------------------------------------
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:45:34.269  WARN 7 --- [  XNIO-2 task-1] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:47:28.150  INFO 7 --- [pool-5-thread-1] i.g.j.r.service.ZuulUpdaterService       : Zuul routes have changed - refreshing the configuration
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:49:08.166  INFO 7 --- [pool-5-thread-1] i.g.j.r.service.ZuulUpdaterService       : Zuul routes have changed - refreshing the configuration
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:50:38.173  INFO 7 --- [pool-5-thread-1] i.g.j.r.service.ZuulUpdaterService       : Zuul routes have changed - refreshing the configuration
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:50:43.176 ERROR 7 --- [pool-5-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
flair-registry-74fbd79fb5-z2lcc flair-registry
flair-registry-74fbd79fb5-z2lcc flair-registry java.lang.NullPointerException: null
flair-registry-74fbd79fb5-z2lcc flair-registry 	at io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes(ZuulUpdaterService.java:65)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at jdk.internal.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.lang.Thread.run(Thread.java:835)
flair-registry-74fbd79fb5-z2lcc flair-registry
flair-registry-74fbd79fb5-z2lcc flair-registry 2020-04-15 12:50:48.177 ERROR 7 --- [pool-5-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
flair-registry-74fbd79fb5-z2lcc flair-registry
flair-registry-74fbd79fb5-z2lcc flair-registry java.lang.NullPointerException: null
flair-registry-74fbd79fb5-z2lcc flair-registry 	at io.github.jhipster.registry.service.ZuulUpdaterService.updateZuulRoutes(ZuulUpdaterService.java:65)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at jdk.internal.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
flair-registry-74fbd79fb5-z2lcc flair-registry 	at java.base/java.lang.Thread.run(Thread.java:835)
flair-registry-74fbd79fb5-z2lcc flair-registry
`

**Comment by admin-vizcentric** [comment] 2020-04-15 18:35
Hi @fabiofilz ,
this also was also spotted by us and it was caused by flair notification, whose eureka client was missing few parameters. 
This issue is fixed with flair-notifications:2.5.3.
Can you try it out?

Kind regards,
Vizcentric Team

**Comment by fabiofilz** [comment] 2020-04-16 10:51
Hi @admin-vizcentric,

Using the flair-notifications:2.5.3 the java.lang.NullPointerException doesnt happen.

Kind regards,
Fabio

**Closed as completed** 2020-04-26 21:19 UTC
